name: alcool_ou_gasolina
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_masked_text2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/aog-white.png    
 
  fonts:
    - family: Big Shoulders Display
      fonts:
        - asset: assets/fonts/BigShouldersDisplay-Light.ttf  